# Generated by Django 5.0.4 on 2026-01-19 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvbuilder", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cvprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Профиль резюме",
                "verbose_name_plural": "Профили резюме",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["order", "-level", "name"],
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="github_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="headline",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("github-dark", "GitHub Dark"),
                    ("github-light", "GitHub Light"),
                    ("dracula", "Dracula"),
                    ("nord", "Nord"),
                ],
                default="github-dark",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cvprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("frontend", "Frontend"),
                    ("backend", "Backend"),
                    ("tools", "Tools & DevOps"),
                    ("mobile", "Mobile"),
                    ("soft", "Soft Skills"),
                ],
                default="tools",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("profile", "name")},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("technologies", models.CharField(blank=True, max_length=500)),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="projects/")),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="cvbuilder.cvprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["order", "-is_featured", "-created_at"],
            },
        ),
    ]
