# Generated by Django 5.0.4 on 2026-01-21 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvbuilder", "0002_alter_cvprofile_options_alter_skill_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Поддерживаемые форматы: JPG, PNG, GIF, WebP. Максимальный размер: 2MB",
                null=True,
                upload_to="avatars/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cvprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Изображение проекта. Максимальный размер: 5MB",
                null=True,
                upload_to="projects/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.IntegerField(default=0, help_text="Порядок отображения"),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.CharField(
                blank=True, help_text="Технологии, разделенные запятыми", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("frontend", "Frontend"),
                    ("backend", "Backend"),
                    ("tools", "Tools & DevOps"),
                    ("mobile", "Mobile"),
                    ("soft", "Soft Skills"),
                ],
                db_index=True,
                default="tools",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=3,
                help_text="Уровень от 1 (новичок) до 5 (эксперт)",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="skill",
            name="order",
            field=models.IntegerField(default=0, help_text="Порядок отображения"),
        ),
    ]
